### PR TITLE
function to list the plug in the plugin

### PR DESCRIPTION
**Pull request by giloser**
Hi,
to be able to use your plugin in mine I needed to list the plug available , so I add a function to get the list.

thanks

Gilles

### CODE REVIEW

**Review by jneilliii — APPROVED** [review]

**Comment by jneilliii** [comment]
could you let me know what plugin this functionality was needed for so I can note it in the release notes properly please?

**Comment by giloser** [comment]
yes of course it's for the telegram plugin.
I'll probably do the same for your TPLink plugin if that's ok :)

**Comment by jneilliii** [comment]
I'm not familiar with how that plugin works, but wouldn't it be easier to pull the settings directly from settings in your plugin? ie `self.settingsViewModel.settings.plugins.tasmotamqtt.arrRelays` rather than another API endpoint?

**Comment by jneilliii** [comment]
actually looking at your code....`self.settings.settings.plugins.tasmotamqtt.arrRelays()`

**Comment by giloser** [comment]
hum ok I'm not really a specialist , but as I have seen how many plugin you did (great job by the way), I will follow and change my way to access. Is the current status saved in the options as well?
thanks

**Comment by jneilliii** [comment]
I'm not saying your approach is bad, just don't know how or where you're implementing this on your side. Current state is currently saved in settings, but that is something that I've been working on separating up like I have done for the non-MQTT Tasmota plugin variant.

**Comment by giloser** [comment]
it's only call to start or stop a printer

**Pull request merged**
